version: '3.8'

services:
  audit-log-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: sjkarthis/audit-log:1.0.2
    container_name: audit-log-app
    volumes:
      - ./app:/app
      - ./config:/config
      - ./local_storage:/app/local_storage
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=prod