apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audit-log-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "audit-log-app.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "audit-log-app.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "audit-log-app.name" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: LOCAL_STORAGE_PATH
              value: /app/local_storage/fallback_data.json
            - name: KAFKA_BROKER_URL
              value: localhost:9092
          volumeMounts:
            - name: local-storage
              mountPath: /app/local_storage
      volumes:
        - name: local-storage
          emptyDir: {}