apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audit-log-app.fullname" . }}
  labels:
    {{- include "audit-log-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "audit-log-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "audit-log-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: LOCAL_STORAGE_PATH
              value: /app/local_storage/fallback_data.json
            - name: KAFKA_BROKER_URL
              value: localhost:9092
          volumeMounts:
            - name: local-storage
              mountPath: /app/local_storage
      volumes:
        - name: local-storage
          emptyDir: {}
