name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: sjkarthis
  IMAGE_NAME: audit-log

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          TAG: latest #${{ github.sha }}
        run: |
          docker-compose build --build-arg TAG=${TAG}
          docker-compose push

      - name: Login to Docker Hub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_KEY

      - name: Push Docker image with specific tag
        run: docker tag $DOCKERHUB_USERNAME/${IMAGE_NAME} $DOCKERHUB_USERNAME/${IMAGE_NAME}:${TAG} && docker push $DOCKERHUB_USERNAME/${IMAGE_NAME}:${TAG}
        