name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: sjkarthis
  IMAGE_NAME: audit-log

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKERHUB_USERNAME -p ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push Docker image
        run: docker-compose build && docker-compose push
